src/Entity/ArticleTriks.php
<?php

namespace App\Entity;

use App\Repository\ArticleTriksRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Service\Slug;

/**
 * @ORM\Entity(repositoryClass=ArticleTriksRepository::class)
 * @UniqueEntity(
 * fields={"NomArtTriks"},
 * message = "Le nom de cette figure est déjà utilisé, veuillez taper un autre nom de figure !")
 */
class ArticleTriks
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $NomArtTriks;

    /**
     * @ORM\Column(type="string", length=70)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $ContenuArtTriks;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCreationArtTriks;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDerniereModificationArtTriks;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="articleTriks", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity=GroupeTriks::class, inversedBy="articleTriks", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Groupe;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="Article", cascade={"remove"})
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=ImageTriks::class, mappedBy="Article", orphanRemoval=true, cascade={"persist"})
     */
    private $imageTriks;

    /**
     * @ORM\OneToMany(targetEntity=VideoTriks::class, mappedBy="Article", orphanRemoval=true, cascade={"persist"})
     */
    private $videoTriks;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->imageTriks = new ArrayCollection();
        $this->videoTriks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomArtTriks(): ?string
    {
        return $this->NomArtTriks;
    }

    public function setNomArtTriks(string $NomArtTriks): self
    {
        $this->NomArtTriks = $NomArtTriks;

        return $this;
    }

    /**
     * slug initialize
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug)) {
            $slugify = new Slug();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
    
    public function setSlug($slug): self
    {
        $slugify = new Slug();
        $this->slug = $slugify->slugify($slug);

        return $this;
    }

    public function getContenuArtTriks(): ?string
    {
        return $this->ContenuArtTriks;
    }

    public function setContenuArtTriks(string $ContenuArtTriks): self
    {
        $this->ContenuArtTriks = $ContenuArtTriks;

        return $this;
    }

    public function getDateCreationArtTriks(): ?\DateTimeInterface
    {
        return $this->DateCreationArtTriks;
    }

    public function setDateCreationArtTriks(\DateTimeInterface $DateCreationArtTriks): self
    {
        $this->DateCreationArtTriks = $DateCreationArtTriks;

        return $this;
    }

    public function getDateDerniereModificationArtTriks(): ?\DateTimeInterface
    {
        return $this->DateDerniereModificationArtTriks;
    }

    public function setDateDerniereModificationArtTriks(\DateTimeInterface $DateDerniereModificationArtTriks): self
    {
        $this->DateDerniereModificationArtTriks = $DateDerniereModificationArtTriks;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    public function getGroupe(): ?GroupeTriks
    {
        return $this->Groupe;
    }

    public function setGroupe(?GroupeTriks $Groupe): self
    {
        $this->Groupe = $Groupe;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ImageTriks[]
     */
    public function getImageTriks(): Collection
    {
        return $this->imageTriks;
    }

    public function addImageTrik(ImageTriks $imageTrik): self
    {
        if (!$this->imageTriks->contains($imageTrik)) {
            $this->imageTriks[] = $imageTrik;
            $imageTrik->setArticle($this);
        }

        return $this;
    }

    public function removeImageTrik(ImageTriks $imageTrik): self
    {
        if ($this->imageTriks->removeElement($imageTrik)) {
            // set the owning side to null (unless already changed)
            if ($imageTrik->getArticle() === $this) {
                $imageTrik->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|VideoTriks[]
     */
    public function getVideoTriks(): Collection
    {
        return $this->videoTriks;
    }

    public function addVideoTrik(VideoTriks $videoTrik): self
    {
        if (!$this->videoTriks->contains($videoTrik)) {
            $this->videoTriks[] = $videoTrik;
            $videoTrik->setArticle($this);
        }

        return $this;
    }

    public function removeVideoTrik(VideoTriks $videoTrik): self
    {
        if ($this->videoTriks->removeElement($videoTrik)) {
            // set the owning side to null (unless already changed)
            if ($videoTrik->getArticle() === $this) {
                $videoTrik->setArticle(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->NomArtTriks;
    }
}

src/Controller/ArticleTriksController.php
<?php

namespace App\Controller;

use App\Entity\ArticleTriks;
use App\Form\ArticleTriksType;
use App\Form\CommentType;
use App\Repository\ArticleTriksRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\ImageTriks;
use App\Entity\VideoTriks;
use App\Entity\Commentaire;
use App\Entity\GroupeTriks;
use App\Entity\Utilisateur;;
use App\Service\FileUploader;
use App\Service\AddImgVid;
use App\Service\PaginatorService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/article/triks")
 */
class ArticleTriksController extends AbstractController
{

    public function __construct()
    {
    }

    /**
     * @Route("article/new", name="article_triks_new", methods={"GET","POST"})
     * 
     * @IsGranted("ROLE_USER")
     */
    public function new(Request $request, FileUploader $fileUploader, AddImgVid $addImgVid): Response
    {
        $articleTrik = new ArticleTriks();
        $imageTriks = new ImageTriks();
        $repositoryImage = $this->getDoctrine()->getRepository(ImageTriks::class);
        $repositoryVideo = $this->getDoctrine()->getRepository(VideoTriks::class);

        $form = $this->createForm(ArticleTriksType::class, $articleTrik);
        $form->handleRequest($request);

        /** @var \App\Entity\Utilisateur $user */
        $user = $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère les images transmises
            $imagesTriksForm = $form->get('LienImgTriks')->getData();
            $videosTriks = $form->get('videoTriks')->getData();
            $groupeTriks = $form->get('Groupe')->getData();
            $repositoryUser = $this->getDoctrine()->getRepository(Utilisateur::class);

            $repositoryArticle = $this->getDoctrine()->getRepository(ArticleTriks::class);
            // $result = $repositoryArticle->addArticle($articleTrik, $user[0]->getId(), $groupeTriks->getId());

            // var_dump($articleTrik->getImageTriks());
        
            // $maxIdArticle = $repositoryArticle->getMaxId();
            // var_dump($maxIdArticle[0]['max_id']);

            // var_dump($imagesTriks);
                
            // $articleTrik->setUtilisateur($user);
            // $user = $repositoryUser->getUserById($userIdSession);
            $articleTrik->setUtilisateur($user);
            $articleTrik->setGroupe($groupeTriks);

            $articleTrik->setSlug($articleTrik->getNomArtTriks());

            // var_dump($imagesTriks);


            /*var_dump($user->getId());

            $varUser = $articleTrik->getUtilisateur();
            var_dump($varUser->getId()); */
            if(!empty($imagesTriksForm) && $imagesTriksForm != NULL){
                /** @var ArticleTriks $articleTrik, @var Array $imagesTriksForm, @var FileUploader $fileUploader, @var String $route */
                $articleTrik = $addImgVid->addImages($articleTrik, $imagesTriksForm, $fileUploader, 'new');    
            } else {
                $imageTriks->setLienImgTriks('NoPicture.jpg');
                $articleTrik->addImageTrik($imageTriks);
            }

                
            // var_dump($videosTriks);
            foreach($videosTriks as $videoTriks){
                /** @var ArticleTriks $articleTrik, @var Array $videosTriks */
                $articleTrik = $addImgVid->addVideos($articleTrik, $videosTriks);
            } 

            $date = new \DateTime("now");
            $articleTrik->setDateCreationArtTriks($date);
            $articleTrik->setDateDerniereModificationArtTriks($date);

            // var_dump($user->getId());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($articleTrik);
            $entityManager->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('article_triks/new.html.twig', [
            'article_trik' => $articleTrik,
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{slug}/show/", name="article_triks_show", methods={"GET", "POST"})
     */
    public function show(Request $request, ArticleTriks $articleTrik, PaginatorService $paginatorService): Response
    {
        $paginator_per_page = 2 + $request->query->getInt('paginator_per_page', 0);
        $repositoryComment = $this->getDoctrine()->getRepository(Commentaire::class);

        /** @var Int $paginator_per_page, @var ArticleTriks $articleTrik, @var CommentaireRepository $repositoryComment */
        $comments = $paginatorService->paginComment($paginator_per_page, $articleTrik, $repositoryComment);

        /** @var \App\Entity\Utilisateur $user */
        $user = $this->getUser();

        $form = $this->createForm(CommentType::class);
        $form->handleRequest($request);

        return $this->render('article_triks/show.html.twig', [
            'article_trik' => $articleTrik,
            'comments_triks' => $comments,
            "next" => min(count($comments), $paginator_per_page),
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}/edit/", name="article_triks_edit", methods={"GET","POST"})
     * 
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, ArticleTriks $articleTrik, FileUploader $fileUploader, AddImgVid $addImgVid): Response
    {
            $form = $this->createForm(ArticleTriksType::class, $articleTrik);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $imagesTriks = $form->get('LienImgTriks')->getData();
                $videosTriks = $form->get('videoTriks')->getData();
                $groupeTriks = $form->get('Groupe')->getData();

                $articleImages = $articleTrik->getImageTriks();
                if($articleImages[0] == NULL && empty($imagesTriks)){
                    $imageTriksArticleEmpty = new ImageTriks();
                    $imageTriksArticleEmpty->setLienImgTriks('NoPicture.jpg');
                    $articleTrik->addImageTrik($imageTriksArticleEmpty);
                }
                foreach($articleImages as $articleImage){
                    if(!empty($request->files->get('image_'.$articleImage->getId())) ){
                        // var_dump('Je suis dans le if avec l"id'.$articleImage->getId());
                        $nom = $articleImage->getLienImgTriks();
                        unlink($this->getParameter('images_directory').'/'.$nom);

                        $imageFile = $request->files->get('image_'.$articleImage->getId());
                        /** @var UploadedFile $imageFile */
                        $imageFileName = $fileUploader->upload($imageFile);

                        $articleImage->setLienImgTriks($imageFileName);
                        $articleTrik->addImageTrik($articleImage);
                    }
                }

                $articleVideos = $articleTrik->getVideoTriks();
                foreach($articleVideos as $articleVideo){
                    if(!empty($request->request->get('video_'.$articleVideo->getId())) ){

                        $videoName = $request->request->get('video_'.$articleVideo->getId());

                        $articleVideo->setLienVidTriks($videoName);
                        $articleTrik->addVideoTrik($articleVideo);
                    }
                }

                /* $imageEditTriks = $request->getParameter('article_triks_image_update');
                var_dump($imageEditTriks); */

                // var_dump($imagesTriks);
                // var_dump($videosTriks);
                // var_dump($groupeTriks->getId());

                if(!empty($imagesTriks)){
                    /** @var ArticleTriks $articleTrik, @var Array $imagesTriksForm, @var FileUploader $fileUploader, @var String $route */
                    $articleTrik = $addImgVid->addImages($articleTrik, $imagesTriks, $fileUploader, 'edit');
                }

                if(!empty($videosTriks)){
                    /** @var ArticleTriks $articleTrik, @var Array $videosTriks */
                    $articleTrik = $addImgVid->addVideos($articleTrik, $videosTriks);
                }

                
                // $repositoryArticle = $this->getDoctrine()->getRepository(ArticleTriks::class);
                // $result = $repositoryArticle->editArticle($articleTrik, $groupeTriks->getId());
                $articleTrik->setSlug($articleTrik->getNomArtTriks());

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($articleTrik);
                $entityManager->flush();
                
                return $this->redirectToRoute('article_triks_show', [ 'slug' => $articleTrik->getSlug() ]);
            }

            return $this->render('article_triks/edit.html.twig', [
                'article_trik' => $articleTrik,
                'form' => $form->createView(),
            ]);
    }

    /**
     * @Route("/delete/image/{id}", name="article_triks_delete_image", methods={"DELETE"})
     * 
     * @IsGranted("ROLE_USER")
     */
    public function deleteImage(ImageTriks $image, Request $request){
        $data = json_decode($request->getContent(), true);

        // On vérifie si le token est valide
        if($this->isCsrfTokenValid('delete'.$image->getId(), $data['_token'])){
            // On récupère le nom de l'image et en dessous on supprime le fichier
            $name = $image->getLienImgTriks();
            unlink($this->getParameter('images_directory').'/'.$name);

            // On supprime l'entrée de la base
            $em = $this->getDoctrine()->getManager();
            $em->remove($image);

templates/article_triks/_delete_form.html.twig
<form method="post" action="{{ path('article_triks_delete', {'id': article_trik.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article_trik.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article_triks/_form_layout.html.twig
{% block addField_articleForm %}
    <div class="d-flex block-img-vid-add">
        <div class="block-img-add">
            <ul id="image-fields-list"
                data-prototype="{{ form_widget(form.LienImgTriks.vars.prototype)|e }}"
                data-widget-tags="{{ '<li></li>'|e }}"
                data-widget-counter="{{ form.LienImgTriks|length }}">
                {% for imageField in form.LienImgTriks %}
                    <li>
                        {{ form_errors(imageField) }}
                        {{ form_widget(imageField) }}
                    </li>
                {% endfor %}
            </ul>
        <button type="button" class="add-another-collection-widget btn-new-image" data-list-selector="#image-fields-list">Ajout image</button>
    </div>    

    <div class="block-vid-add">
        <ul id="video-fields-list"
            data-prototype="{{ form_widget(form.videoTriks.vars.prototype)|e }}"
            data-widget-tags="{{ '<li></li>'|e }}"
            data-widget-counter="{{ form.videoTriks|length }}">
            {% for videoField in form.videoTriks %}
                <li>
                    {{ form_errors(videoField) }}
                    {{ form_widget(videoField) }}
                </li>
            {% endfor %}
        </ul>
        <button type="button" class="add-another-collection-widget btn-new-video" data-list-selector="#video-fields-list">Ajout vidéo</button>
    </div>
</div>
{% endblock addField_articleForm %}

templates/article_triks/_show_layout.html.twig
{% block img_vid_articleFile %}
<div class="bg-light">
    <div class="d-flex justify-content-center">
        <div class="block-img">
            <figure>
                <div class="index-img">
                    <div class="btn-group d-flex justify-content-end">
                        <div class="edit-btn">
                            <a href="{{ path('article_triks_edit', {'slug': article_trik.slug}) }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>
                            </a>
                        </div>
                    </div>
                    <img class="img-thumbnail-article" src="{{ asset('/uploads/imagesArticle/' ~ article_trik.imageTriks[0].LienImgTriks) }}" alt="Image de tricks de snowboard">                                         
                </div>
                <figcaption class="figcaption-articleName">{{ article_trik.NomArtTriks }}</figcaption>
            </figure>                     
        </div>
    </div>

    <div class="album py-4 ">
        <div class="container">
            <div class="see-display">
                <button class="btn-user" id="display-hide-see-article-show">Afficher / cacher images et vidéos</button>
            </div>
            <div class="row justify-content-center hide-display display-image-vid-show" id="display-images-videos-article-show">
            {% for imageTriks in article_trik.imageTriks %}
                {% if not loop.first %}
                    <div class="col-md-3" >
                        <div class="card mb-3 shadow-sm">
                            <img class="img-article" src="{{ asset('/uploads/imagesArticle/' ~ imageTriks.LienImgTriks) }}" />
                        </div>
                    </div>   
                {% endif %}
            {% endfor %}
            {% for videoTriks in article_trik.videoTriks %}
                <div class="col-md-3">
                    <iframe src="{{ videoTriks.LienVidTriks }}">
                    </iframe>                        
                </div> 
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock img_vid_articleFile %}

{% block info_articleFile %}                          
<div class="d-flex justify-content-center text-wrap">
    <div class="block-text">
        <div class="text-left">
            {{ article_trik.ContenuArtTriks }}
        </div>
        <div class="d-flex justify-content-center group-article-show"> 
            <div class="group-border">Crée le : {{ article_trik.DateCreationArtTriks ? article_trik.DateCreationArtTriks|date('Y-m-d') : '' }}</div>
            <div class="group-border">Groupe : {{ article_trik.groupe.NomGrpTriks }}</div>
            <div class="group-border">Dernière modification le : {{ article_trik.DateDerniereModificationArtTriks ? article_trik.DateDerniereModificationArtTriks|date('Y-m-d') : '' }}</div>
        </div>
{% endblock info_articleFile %} 

{% block comment_articleFile %}
    <div class="see-display">
        <button class="btn-user" id="display-hide-see-comment-article-show">Afficher / cacher les commentaires</button>
    </div>
    <div class="row justify-content-center block-comment-user hide-display" id="display-comment-article-show">
    {% for commentTriks in comments_triks %}
        <div class="img-user-comment">
            <img class="round-image" src="{{ asset('/uploads/imagesUser/' ~ commentTriks.Utilisateur.PhotoUtilisateur) }}"/>
        </div>
        <div class="block-comment">
            <div class="pseudo-comment">
                {{ commentTriks.Utilisateur.username }}
                ({{ article_trik.DateCreationArtTriks ? commentTriks.DateCommentaire|date('Y-m-d') : '' }}) :
            </div>
            <div class="text-comment">
                {{ commentTriks.ContenuCommentaire }}
            </div>
        </div>
    {% endfor %}
{% endblock comment_articleFile %}

{% block loadMoreComment_articleFile %}
            {% if next < comments_triks|length %}
            <div class="container">
                <div class="d-flex justify-content-center">
                    <a href="{{ path('article_triks_show', { 
                        paginator_per_page: next,
                        'slug': article_trik.slug
                    }) }}">Load more</a>
                </div>  
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock loadMoreComment_articleFile %}

templates/article_triks/edit.html.twig
{% extends 'base.html.twig' %} 

    {% block main %}               
        <h1 class="titre-new">Modification de l'article</h1>

        {{ include('article_triks/_form.html.twig') }}
    {% endblock main %}             
                
    {% block javascripts %}
    {% endblock %}

templates/article_triks/new.html.twig
{% extends 'base.html.twig' %} 

      {% block main %}               
        <h1 class="titre-new">Nouvel article</h1>

        {{ include('article_triks/_form.html.twig') }}
    {% endblock main %}

    {% block javascripts %}
    {% endblock %}

templates/article_triks/show.html.twig
{% extends 'base.html.twig' %} 

    {% block main %} 
        {% use "article_triks/_show_layout.html.twig" with img_vid_articleFile as parent_imgVid, info_articleFile as parent_info, comment_articleFile as parent_comment, loadMoreComment_articleFile as parent_loadMore %} 

        {% block img_vid_articleFile %} {{ block('parent_imgVid') }} {% endblock img_vid_articleFile %}

        {% block info_articleFile %} {{ block('parent_info') }} {% endblock info_articleFile %}

        {% if user is defined and user != null %}
            <hr class="article">
            <div class="d-flex justify-content-center">
                {{ form(form, {'action': path('new_comment', {slug: article_trik.slug})} ) }}
            </div>
        {% endif %}
        <hr class="article">

        {% block comment_articleFile %} {{ block('parent_comment') }} {% endblock comment_articleFile %}

        {% block loadMoreComment_articleFile %} {{ block('parent_loadMore') }} {% endblock loadMoreComment_articleFile %}
    {% endblock main %}

    {% block javascripts %}
        <script src="{{ asset('js/changeDisplayField.js') }}"></script>
    {% endblock %}