src/Entity/ArticleTriks.php
<?php

namespace App\Entity;

use App\Repository\ArticleTriksRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Service\Slug;

/**
 * @ORM\Entity(repositoryClass=ArticleTriksRepository::class)
 * @UniqueEntity(
 * fields={"NomArtTriks"},
 * message = "Le nom de cette figure est déjà utilisé, veuillez taper un autre nom de figure !")
 */
class ArticleTriks
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $NomArtTriks;

    /**
     * @ORM\Column(type="string", length=70)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $ContenuArtTriks;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCreationArtTriks;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDerniereModificationArtTriks;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="articleTriks", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity=GroupeTriks::class, inversedBy="articleTriks", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Groupe;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="Article", cascade={"remove"})
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=ImageTriks::class, mappedBy="Article", orphanRemoval=true, cascade={"persist"})
     */
    private $imageTriks;

    /**
     * @ORM\OneToMany(targetEntity=VideoTriks::class, mappedBy="Article", orphanRemoval=true, cascade={"persist"})
     */
    private $videoTriks;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->imageTriks = new ArrayCollection();
        $this->videoTriks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomArtTriks(): ?string
    {
        return $this->NomArtTriks;
    }

    public function setNomArtTriks(string $NomArtTriks): self
    {
        $this->NomArtTriks = $NomArtTriks;

        return $this;
    }

    /**
     * slug initialize
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug)) {
            $slugify = new Slug();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
    
    public function setSlug($slug): self
    {
        $slugify = new Slug();
        $this->slug = $slugify->slugify($slug);

        return $this;
    }

    public function getContenuArtTriks(): ?string
    {
        return $this->ContenuArtTriks;
    }

    public function setContenuArtTriks(string $ContenuArtTriks): self
    {
        $this->ContenuArtTriks = $ContenuArtTriks;

        return $this;
    }

    public function getDateCreationArtTriks(): ?\DateTimeInterface
    {
        return $this->DateCreationArtTriks;
    }

    public function setDateCreationArtTriks(\DateTimeInterface $DateCreationArtTriks): self
    {
        $this->DateCreationArtTriks = $DateCreationArtTriks;

        return $this;
    }

    public function getDateDerniereModificationArtTriks(): ?\DateTimeInterface
    {
        return $this->DateDerniereModificationArtTriks;
    }

    public function setDateDerniereModificationArtTriks(\DateTimeInterface $DateDerniereModificationArtTriks): self
    {
        $this->DateDerniereModificationArtTriks = $DateDerniereModificationArtTriks;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    public function getGroupe(): ?GroupeTriks
    {
        return $this->Groupe;
    }

    public function setGroupe(?GroupeTriks $Groupe): self
    {
        $this->Groupe = $Groupe;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ImageTriks[]
     */
    public function getImageTriks(): Collection
    {
        return $this->imageTriks;
    }

    public function addImageTrik(ImageTriks $imageTrik): self
    {
        if (!$this->imageTriks->contains($imageTrik)) {
            $this->imageTriks[] = $imageTrik;
            $imageTrik->setArticle($this);
        }

        return $this;
    }

    public function removeImageTrik(ImageTriks $imageTrik): self
    {
        if ($this->imageTriks->removeElement($imageTrik)) {
            // set the owning side to null (unless already changed)
            if ($imageTrik->getArticle() === $this) {
                $imageTrik->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|VideoTriks[]
     */
    public function getVideoTriks(): Collection
    {
        return $this->videoTriks;
    }

    public function addVideoTrik(VideoTriks $videoTrik): self
    {
        if (!$this->videoTriks->contains($videoTrik)) {
            $this->videoTriks[] = $videoTrik;
            $videoTrik->setArticle($this);
        }

        return $this;
    }

    public function removeVideoTrik(VideoTriks $videoTrik): self
    {
        if ($this->videoTriks->removeElement($videoTrik)) {
            // set the owning side to null (unless already changed)
            if ($videoTrik->getArticle() === $this) {
                $videoTrik->setArticle(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->NomArtTriks;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\ArticleTriks;
use App\Entity\ImageTriks;
use Doctrine\ORM\EntityManagerInterface;


class HomeController extends AbstractController 
{
    public function __construct()
    {
    }

    /**
     * @Route("/", name="home")
     */
    public function home(Request $request): Response
    {
        // Var
        $paginator_per_page = 5 + $request->query->getInt('paginator_per_page', 0);
        $i = 1;
        $repositoryArticles = $this->getDoctrine()->getRepository(ArticleTriks::class);

        // Collect articles from the Database 
        $paginArticles = $repositoryArticles->getPaginArticle($paginator_per_page);

        return $this->render('home/home.html.twig', [
            "articles" => $paginArticles,
            "next" => min(count($paginArticles), $paginator_per_page),
        ]);
    }
}

templates/home/_home_layout.html.twig
{% block articleList %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for article in articles %}
            {#{{ dump(article.imageTriks) }} #}
            {# {{ dump(images) }} #}
            {# {{ dump(imageArt) }} #}
            {% for imageTriks in article.imageTriks %}
                {% if loop.first %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <svg height="0"><img src="{{ asset('/uploads/imagesArticle/' ~ imageTriks.LienImgTriks) }}" width="100%" height="250px"/></svg>
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{{ path('article_triks_show', { 'slug': article.slug }) }}">{{ article.nomArtTriks }}</a>
                                <div class="btn-group d-flex">
                                    <div class="edit-btn">
                                        <a href="{{ path('article_triks_edit', {'slug': article.slug}) }}">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                            </svg>
                                        </a>
                                    </div>
                                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                    <form method="post" action="{{ path('article_triks_delete', {'slug': article.slug}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer cet article?');">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
                                        <button class="btn btn-sm btn-outline-secondary">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                            </svg>
                                        </button>
                                    </form>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
                {% endif %}
            {% endfor %}
        {% endfor %}                               
        </div>
    </div>
</div>
{% endblock articleList %}

{% block loadMoreArticle %}
{% if next < articles|length %}
    <div class="container">
        <div class="d-flex justify-content-center">
            <a href="{{ path('home', { paginator_per_page: next }) }}">Load more</a>
        </div>  
    </div>
{% endif %}
{% endblock loadMoreArticle %}

templates/home/home.html.twig
{% extends 'base.html.twig' %}
        
    {# Cover part #}
    {% block main %}  
        <h1 class="cover-heading">TriksPédia</h1>
        <p class="lead">Un site vous permettant de tout savoir sur les triks en snowboard.</p>                                       
    {% endblock main %} 
    {# End of cover part #}

    {% block body %}
        {% use "home/_home_layout.html.twig" with articleList as parent_articleList, loadMoreArticle as parent_loadMoreArticle %}
        {# Triks part #}
        <section id="triks">
            {% block articleList %}
                {{ block('parent_articleList') }}
            {% endblock articleList %}
        </section>
        {# End of triks part #}

        {# "Load more" part #}
        {% block loadMoreArticle %}
            {{ block('parent_loadMoreArticle') }}
        {% endblock loadMoreArticle %}            
        {# End of "Load more" part #}
    {% endblock body %}
{% block javascripts %}{% endblock %}